### ISSUE TITLE
添加 addr=0.0.0.0:5211 本地监听端口还是1234

### ISSUE THREAD

**Issue by shinexiong1987** [cmliu/CFnat-Docker#1]
docker run -d -e colo="HKG" -e delay=160 -e ips=4 -e port=80 -e addr=0.0.0.0:5211 -e tls=false -p 5211:5211 cmliu/cfnat:latest

用以上shell 部署出现本地监听端口还是1234，导致无法连接

**Comment by cmliu** [comment]
> docker run -d -e colo="HKG" -e delay=160 -e ips=4 -e port=80 -e addr=0.0.0.0:5211 -e tls=false -p 5211:5211 cmliu/cfnat:latest
> 
> 用以上shell 部署出现本地监听端口还是1234，导致无法连接

你只需要修改外部映射端口就可以了，不需要修改容器内的端口，项目说明里有示例啊
docker run -d -e colo="HKG" -e delay=160 -e ips=4 -e port=80 -e tls=false -p 5211:1234 cmliu/cfnat:latest
