### ISSUE TITLE
增加IPV6

### ISSUE THREAD

**Issue by ekko440** [cmliu/CFnat-Docker#5]
希望能把IPV6加上去，有些地区只有IPV6的地址。

**Comment by conanx2008** [comment]
cm不欠你的吧？你这口气让我都不不爽了

**Comment by cmliu** [comment]
> 希望能把IPV6加上去，有些地区只有IPV6的地址。

docker的ip6的问题主要是，docker自身没有ip6，这个我也无能为力的，只要是有ip6的环境cfnat是有能跑ip6的能力的
